image: docker:27.3.1

services:
  - docker:27.3.1-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

before_script:
  - apk add --no-cache docker-cli-compose

build-compose:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker info
    - docker compose version
    - docker compose build --pull --no-cache