version: "3.9"

services:

  app:
    build: .

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://91.107.126.43:5432/${POSTGRES_DB:-homerep_userservice}}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER:-postgres}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD:-postgres}}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      HOMEREP_SECRET: ${HOMEREP_SECRET:?HOMEREP_SECRET is not set}
      HOMEREP_LIFETIME: ${HOMEREP_LIFETIME:-600000}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:-91.107.126.43:9092}
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_SECURITY_USER_NAME: ${APP_USER:-admin}
      SPRING_SECURITY_USER_PASSWORD: ${APP_PASSWORD:-admin}
      SPRING_SECURITY_USER_ROLE: ${APP_ROLE:-AGENT}
      SPRING_KAFKA_CONSUMER_GROUP_ID: hostmaster-group
    ports:
      - "8080:8080"
